// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdalbvizzftlqdnwvjdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkYWxidml6emZ0bHFkbnd2amRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzU3NjUsImV4cCI6MjA2OTU1MTc2NX0.c4cdg4fopZxgcIs39TanvmyUT0wB3flRaNzzDds1Irg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});